apiVersion: v1
kind: Pod
metadata:
  name: mariadb
  namespace: default
spec:
  containers:
    - name: mariadb

      image: mariadb:latest
      env:
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: debook-secret
              key: db.password
      volumeMounts:
        - name: mariadb-storage
          mountPath: /var/lib/mariadb
        - name: init-sql
          mountPath: /docker-entrypoint-initdb.d/init.sql
          subPath: init.sql
  volumes:
    - name: mariadb-storage
      persistentVolumeClaim:
        claimName: mariadb-pvc
    - name: init-scripts
      configMap:
        name: mariadb-init-scripts  # ConfigMap 이름

      