apiVersion: v1

kind: Service

metadata:
  name: boot001ser
  namespace: default
spec:
  type: NodePort

  ports:
    - port: 8001
      targetPort: 8080
      protocol: TCP
      nodePort: 30001 # 클러스터의 모든 노드에서 이 포트를 통해 서비스에 접근할 수 있다.(30000 ~ 32767)

  selector:
    app: boot001kube
