apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  namespace: default
  labels:
    app: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: mariadb:latest # MariaDB 공식 이미지
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "root" # 루트 비밀번호 설정
            - name: MYSQL_DATABASE
              value: "debook_db"  # 초기화할 데이터베이스 이름
            - name: MYSQL_USER
              value: "debook"
            - name: MYSQL_PASSWORD
              value: "debook"
          volumeMounts:
            - name: init-sql-volume
              mountPath: /docker-entrypoint-initdb.d  # MariaDB 초기화 디렉토리
      volumes:
      - name: init-sql-volume
        persistentVolumeClaim:
          claimName: mariadb-pvc
