apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: default
  name: secret-access-rolebinding
subjects:
  - kind: ServiceAccount
    name: default # Pod에서 사용하는 ServiceAccount 이름
    namespace: default
roleRef:
  kind: Role
  name: secret-access-role
  apiGroup: rbac.authorization.k8s.io
