apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: secret-access-role
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["debook-secret"] # 특정 Secret만 지정
    verbs: ["get", "list"]
