apiVersion: v1
kind: Secret
metadata:
  name: debook-secret
  namespace: default
type: Opaque
data: # api-key.yml에 있던 코드들을 base64 형식으로 인코딩
  db.port: MzMwNg==
  db.dbname: ZGVib29rX2Ri
  db.username: cm9vdA==
  db.password: cm9vdA==
  kakao.client_id.rest_api_key: Yjc5ZjVlMTZhNDdkYWYwZDM1OGExNTVmMDk5ZDgzMzA=
  kakao.redirect_uri: aHR0cDovL2xvY2FsaG9zdDo4MDgwL2FwaS92MS9hdXRoL2NhbGxiYWNr
  token.secret: Sm5TOEl1WkwwQnYyQ0F5N28xVk85cXc5Y2U5ZnBZcVpWbGpQOVpoTEhVN1FpaUkvZ3lOZ1VNZUsxSTdnRHJIRDJMWTRaeW5tWVk5YkhTOW4zQXhOMXc9PQ==
  token.access_token_expiration_time: MTgwMA==
  token.refresh_token_expiration_time: NjA0ODAw
  redis.data.host: bG9jYWxob3N0
  redis.data.port: NjM3OQ==
  s3.bucket: ZGVib29r
  im.access: QUtJQVo1VEM0MlVBVUpWUkw3WE0=
  im.secret: ZkhGT1B1L2prOHBadFR3d1oxT0U0Wmh3MlpPRVd6ZlFsK1YxbzJjTg==
